runtime: java21
instance_class: F1

env_variables:
  SPRING_PROFILES_ACTIVE: "prod"
  GOOGLE_CLOUD_PROJECT: ${GOOGLE_CLOUD_PROJECT}
  FIRESTORE_PROJECT_ID: ${FIRESTORE_PROJECT_ID}
  CLIENT_URL_DEV: ${CLIENT_URL_DEV}
  PORT: "8080"

handlers:
  - url: /.*
    script: auto
    secure: always

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10
  target_throughput_utilization: 0.6
