spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
  config:
    import:
      - "configtree:./"
server:
  servlet:
    context-path: /api

cors:
  allowedOrigins: ${CLIENT_URL_DEV}

runtime: java21
instance_class: ${INSTANCE_CLASS}